'use client'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CalendarCheck2, Loader2, Pencil } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { apiRequest } from '@/lib/client/api'
import type { PlanDecision, PlanResourceEnvelope } from '@/lib/contracts/planning-contracts'
import type { HumanOSTask } from '@/lib/contracts/task-contracts'
import { useEvents } from '@/hooks/use-events'
import { useTranslation } from '@/i18n/LanguageProvider'

export function PlanReviewPanel() {
  const { locale } = useTranslation(); const { refetchEvents } = useEvents(); const [plan, setPlan] = useState<PlanDecision | null>(null); const [tasks, setTasks] = useState<HumanOSTask[]>([]); const [loading, setLoading] = useState(true); const [confirming, setConfirming] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); try { const [p, t] = await Promise.all([apiRequest<PlanResourceEnvelope<{ plan: PlanDecision | null }>>('/api/plans/proposed'), apiRequest<{ data: { tasks: HumanOSTask[] } }>('/api/tasks')]); setPlan(p.data.plan); setTasks(t.data.tasks || []); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Plan review unavailable') } finally { setLoading(false) } }, [])
  useEffect(() => { void load(); const refresh = () => void load(); window.addEventListener('humanos:plan-revision', refresh); return () => window.removeEventListener('humanos:plan-revision', refresh) }, [load])
  const titles = useMemo(() => new Map(tasks.map((task) => [String(task.id), task.title || 'Untitled'])), [tasks])
  const confirm = async () => { if (!plan?.plan_id) return; setConfirming(true); try { const payload = { ...plan, plan_id: plan.plan_id, week_id: plan.week_id, plan_patch: plan.plan_patch || [], unscheduled_tasks: plan.unscheduled_tasks || [] }; const envelope: any = await apiRequest('/api/schedules/validate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const validation = envelope?.validation || envelope?.data?.validation || envelope; if (validation?.valid === false) { const violation = validation.violations?.[0] || {}; if (violation.type === 'unexplained_unallocated_work') { const title = titles.get(String(violation.task_id)) || violation.task_id; throw new Error(locale === 'zh' ? `任务“${title}”仍有 ${violation.remaining || 0} 分钟未安排。任务列表已变化，请重新生成计划。` : `Task “${title}” still has ${violation.remaining || 0} unallocated minutes. Tasks changed; regenerate the plan.`) } throw new Error(violation.message || violation.type || 'Plan violates hard constraints') } await apiRequest('/api/schedules/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); toast.success(locale === 'zh' ? '整份计划已加入日历' : 'The full plan was added to your calendar'); setPlan(null); await refetchEvents(); window.dispatchEvent(new CustomEvent('humanos:plan-revision')) } catch (e) { toast.error(e instanceof Error ? e.message : 'Plan confirmation failed') } finally { setConfirming(false) } }
  if (loading) return <aside className="grid w-80 shrink-0 place-items-center border-l bg-background"><Loader2 className="h-5 w-5 animate-spin" /></aside>
  if (error) return <aside className="w-80 shrink-0 border-l bg-background p-4"><div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300">{error}<Button className="mt-3 w-full" variant="outline" size="sm" onClick={() => void load()}>{locale === 'zh' ? '重试' : 'Retry'}</Button></div></aside>
  if (!plan) return <aside className="flex w-80 shrink-0 flex-col border-l bg-background p-5"><h2 className="font-semibold">{locale === 'zh' ? '计划审查' : 'Plan Review'}</h2><div className="mt-8 rounded-2xl border border-dashed bg-muted/30 p-5 text-center"><CalendarCheck2 className="mx-auto h-5 w-5 text-muted-foreground" /><p className="mt-2 text-sm">{locale === 'zh' ? '当前没有等待确认的计划草案' : 'No draft plan is waiting for confirmation'}</p><Button asChild className="mt-4" size="sm" variant="outline"><Link href="/app/plan">{locale === 'zh' ? '打开周计划' : 'Open weekly plan'}</Link></Button></div></aside>
  return <aside className="flex w-80 shrink-0 flex-col border-l bg-background"><div className="border-b p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">{locale === 'zh' ? '日历安排草案' : 'Calendar Draft'}</h2><span className="rounded-full border border-dashed border-primary/50 bg-primary/10 px-2 py-1 text-[10px] font-semibold text-primary">DRAFT · R{plan.plan_revision || 1}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{locale === 'zh' ? '任务已保存并完成排期。这里只需要最终确认一次，确认后草案会消失并进入正式日历。' : 'Tasks are saved and scheduled. Confirm this draft once to publish it; the draft then disappears.'}</p></div><div className="min-h-0 flex-1 overflow-y-auto p-3">{(plan.plan_patch || []).map((block, index) => <article key={block.block_id || `${block.task_id}-${index}`} className="mb-2 rounded-xl border border-dashed border-border bg-card p-3 text-card-foreground"><div className="flex justify-between gap-2"><div><h3 className="text-sm font-medium">{block.title || titles.get(String(block.task_id)) || block.task_id}</h3><p className="mt-1 text-xs text-muted-foreground">{locale === 'zh' ? `第 ${Number(block.day_index) + 1} 天` : `Day ${Number(block.day_index) + 1}`} · {String(block.start)}–{String(block.end)} · {block.planned_work_minutes || block.session_minutes || 0} min</p></div><Button asChild size="icon" variant="ghost" className="h-7 w-7"><Link href="/app/plan"><Pencil className="h-3.5 w-3.5" /></Link></Button></div></article>)}{(plan.unscheduled_tasks || []).length > 0 && <div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300"><div className="mb-2 flex gap-2 font-semibold"><AlertTriangle className="h-4 w-4" />{locale === 'zh' ? '以下任务无法完整排入' : 'These tasks do not fully fit'}</div>{(plan.unscheduled_tasks || []).map((item) => <div key={String(item.task_id)} className="mt-2 rounded-lg bg-background/70 p-2"><strong>{titles.get(String(item.task_id)) || item.task_id}</strong><p className="mt-1">{item.remaining_minutes || 0} min · {item.reason === 'no_available_interval_before_deadline' ? (locale === 'zh' ? '截止时间前没有足够空闲时间' : 'Not enough free time before the deadline') : (locale === 'zh' ? '可用时间不足' : 'Not enough available time')}</p></div>)}</div>}</div><div className="border-t p-4"><Button className="w-full rounded-xl" disabled={confirming || !plan.plan_patch?.length || Boolean(plan.unscheduled_tasks?.length)} onClick={() => void confirm()}>{confirming && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{locale === 'zh' ? '确认并加入正式日历' : 'Confirm & Publish Calendar'}</Button><Button asChild variant="ghost" className="mt-2 w-full" size="sm"><Link href="/app/plan">{locale === 'zh' ? '调整草案' : 'Adjust draft'}</Link></Button></div></aside>
}
