'use client'
import { useEffect, useRef, useState } from 'react'
import { Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useTranslation } from '@/i18n/LanguageProvider'

interface Props { focusChatTrigger: number; onSendMessage: (message: string) => Promise<any> }
export function WorkspaceSidebar({ focusChatTrigger, onSendMessage }: Props) {
  const { t, locale } = useTranslation(); const input = useRef<HTMLTextAreaElement>(null); const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Array<{ role: string; content: string }>>([])
  useEffect(() => { if (focusChatTrigger > 0) input.current?.focus() }, [focusChatTrigger])
  useEffect(() => { const receive = (event: Event) => { setText(String((event as CustomEvent<{ text?: string }>).detail?.text || '')); window.setTimeout(() => input.current?.focus(), 0) }; window.addEventListener('humanos:planner-handoff', receive); return () => window.removeEventListener('humanos:planner-handoff', receive) }, [])
  const send = async () => { const message = text.trim(); if (!message || loading) return; setText(''); setMessages((list) => [...list, { role: 'user', content: message }]); setLoading(true); try { const data = await onSendMessage(message); if (data?.turn?.reply) setMessages((list) => [...list, { role: 'assistant', content: data.turn.reply }]) } finally { setLoading(false) } }
  return <aside className="flex h-full w-72 shrink-0 flex-col border-r bg-background"><header className="border-b px-4 py-3"><h2 className="text-sm font-semibold">{locale === 'zh' ? '任务规划助手' : 'Task Planner'}</h2><p className="mt-1 text-[11px] text-muted-foreground">{locale === 'zh' ? '理解新增或修改意图，写入前始终预览' : 'Understands changes and always previews before saving'}</p></header><div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-3">{messages.length === 0 && <div className="rounded-xl border border-dashed p-4 text-center text-xs text-muted-foreground">{t('workspace.assistantHint')}</div>}{messages.map((message, index) => <div key={index} className={`rounded-xl p-2.5 text-xs leading-5 ${message.role === 'user' ? 'ml-5 bg-primary text-primary-foreground' : 'mr-5 border bg-card text-card-foreground'}`}>{message.content}</div>)}</div><div className="border-t p-3"><textarea ref={input} rows={3} className="w-full resize-none rounded-xl border bg-background p-3 text-xs outline-none focus:ring-2 focus:ring-primary" value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send() } }} placeholder={t('workspace.assistantHint')} /><div className="mt-2 flex items-center justify-between"><Button variant="ghost" size="sm" onClick={() => input.current?.focus()}><Plus className="mr-1 h-3.5 w-3.5" />{t('workspace.addTask')}</Button><Button size="sm" disabled={loading || !text.trim()} onClick={() => void send()}>{t('workspace.send')}</Button></div></div></aside>
}
